// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission08_4_2.Models;

#nullable disable

namespace Mission08_4_2.Migrations
{
    [DbContext(typeof(TasksContext))]
    [Migration("20240229185439_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Mission08_4_2.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Home"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "School"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Work"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Church"
                        });
                });

            modelBuilder.Entity("Mission08_4_2.Models.Quadrant", b =>
                {
                    b.Property<int>("QuadrantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuadrantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QuadrantID");

                    b.ToTable("Quadrants");

                    b.HasData(
                        new
                        {
                            QuadrantID = 1,
                            QuadrantName = "Urgent/Important"
                        },
                        new
                        {
                            QuadrantID = 2,
                            QuadrantName = "Not Urgent/Important"
                        },
                        new
                        {
                            QuadrantID = 3,
                            QuadrantName = "Urgent/Not Important"
                        },
                        new
                        {
                            QuadrantID = 4,
                            QuadrantName = "Not Urgent/Not Important"
                        });
                });

            modelBuilder.Entity("Mission08_4_2.Models.Tasks", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuadrantID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("QuadrantID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Mission08_4_2.Models.Tasks", b =>
                {
                    b.HasOne("Mission08_4_2.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mission08_4_2.Models.Quadrant", "Quadrant")
                        .WithMany()
                        .HasForeignKey("QuadrantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Quadrant");
                });
#pragma warning restore 612, 618
        }
    }
}
